Removed unnecessary is fetching
CodersCrew/coderscamp-app pull request #36
Opened 2021-06-15 15:36 UTC by lagdush

In the ManageSheet component the message 'is loading...' was displayed, I added a loader here. Removed isFetching from: ReusableTable and connected components, from SectionView and CourseList components.

2021-06-15 19:45 UTC, KrystianKjjk commented on frontend/src/pages/Admin/ManageSheet/ManageSheet.tsx
> +   if (loading === 'loading') return <LinearProgress />
change that loading to 'isLoading' from query, and remove that 'loading' state from component :)

2021-06-16 08:42 UTC, hoolek77 requested changes

2021-06-16 08:42 UTC, hoolek77 commented on frontend/src/components/FindModal/FindModal.tsx
>                    onRowClick={handleRowClick}
Refactor this file and use destructuring for all the props. I know it's not your main goal for this issue, but the component would much cleaner 😎

2021-06-16 18:12 UTC, hoolek77 approved these changes

2021-06-21 16:30 UTC, KrystianKjjk approved these changes

2021-06-21 16:38 UTC, merged